module.exports = {
  API: {
    ERR_NOT_FOUND: 'ERR_NOT_FOUND',
    ERR_VALIDATION: 'ERR_VALIDATION',
    ERR_GENERAL: 'ERR_GENERAL',
    ERR_UNAUTHORIZED: 'ERR_UNAUTHORIZED',
    SUCCESS: 'SUCCESS'
  }
}
